// <auto-generated />
using System;
using GithubSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GithubSync.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GithubSync.Data.Entities.CanonicalActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceActorLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceActorId")
                        .IsUnique();

                    b.ToTable("CanonicalActors");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.CanonicalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventKind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceEntityType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceEventId")
                        .HasColumnType("text");

                    b.Property<Guid>("SyncConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("SyncConfigurationId");

                    b.HasIndex("Source", "SourceEntityType", "SourceEntityId", "EventKind", "EventTime", "SourceEventId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Source", "SourceEntityType", "SourceEntityId", "EventKind", "EventTime", "SourceEventId"), false);

                    b.ToTable("CanonicalEvents");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.DeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CanonicalEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetSystem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalEventId", "Resolved");

                    b.ToTable("DeadLetters");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.IdentityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MappingSource")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSystem")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUserDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalActorId", "TargetSystem")
                        .IsUnique();

                    b.ToTable("IdentityMappings");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.SyncConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetLocator")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TargetSystem")
                        .HasColumnType("integer");

                    b.Property<string>("TargetTypeMapping")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceLocator", "TargetSystem", "TargetLocator")
                        .IsUnique();

                    b.ToTable("SyncConfigurations");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.SyncCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastETag")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastEventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRunCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRunMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastRunStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("SyncConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SyncConfigurationId")
                        .IsUnique();

                    b.ToTable("SyncCursors");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.TargetUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("TargetSystem")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUserDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TargetSystem", "TargetUserId")
                        .IsUnique();

                    b.ToTable("TargetUsers");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.WorkItemMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceEntityType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SyncConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetSystem")
                        .HasColumnType("integer");

                    b.Property<string>("TargetWorkItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SyncConfigurationId", "TargetSystem", "TargetEntityId")
                        .IsUnique();

                    b.HasIndex("SyncConfigurationId", "Source", "SourceEntityType", "SourceEntityId")
                        .IsUnique();

                    b.ToTable("WorkItemMappings");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.CanonicalEvent", b =>
                {
                    b.HasOne("GithubSync.Data.Entities.CanonicalActor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GithubSync.Data.Entities.SyncConfiguration", "SyncConfiguration")
                        .WithMany("Events")
                        .HasForeignKey("SyncConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("SyncConfiguration");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.DeadLetter", b =>
                {
                    b.HasOne("GithubSync.Data.Entities.CanonicalEvent", "CanonicalEvent")
                        .WithMany()
                        .HasForeignKey("CanonicalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalEvent");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.IdentityMapping", b =>
                {
                    b.HasOne("GithubSync.Data.Entities.CanonicalActor", "CanonicalActor")
                        .WithMany()
                        .HasForeignKey("CanonicalActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalActor");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.SyncCursor", b =>
                {
                    b.HasOne("GithubSync.Data.Entities.SyncConfiguration", "SyncConfiguration")
                        .WithOne("Cursor")
                        .HasForeignKey("GithubSync.Data.Entities.SyncCursor", "SyncConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncConfiguration");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.WorkItemMapping", b =>
                {
                    b.HasOne("GithubSync.Data.Entities.SyncConfiguration", "SyncConfiguration")
                        .WithMany("WorkItemMappings")
                        .HasForeignKey("SyncConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SyncConfiguration");
                });

            modelBuilder.Entity("GithubSync.Data.Entities.SyncConfiguration", b =>
                {
                    b.Navigation("Cursor");

                    b.Navigation("Events");

                    b.Navigation("WorkItemMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
